title: "Mingxuan Lu"
author: "Mingxuan Lu"
description: "Columbia University in the City of New York"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Lu_Mingxuan_ml4799_MSEE.pdf", title="CV"}
  - {title: "About me", url: "https://github.com/LouieBHLu/LouieBHLu/blob/main/README.md"}
  


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "ml4799@columbia.edu"}
  - {title: Github, icon: github, url: "https://github.com/LouieBHLu"}
#   - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
